### ISSUE TITLE
about  SplitSABlock 

### ISSUE THREAD

**Issue by x2ss** [Sense-X/UniFormer#10]
Hi,

When I reading the video uniformer code, there is a [SplitSABlock](https://github.com/Sense-X/UniFormer/blob/main/video_classification/slowfast/models/uniformer.py#L165) , and the default setting of enabling it is [false](https://github.com/Sense-X/UniFormer/blob/main/video_classification/slowfast/config/defaults.py#L436) .

However, I can't find this split block in[ "UniFormer: Unifying Convolution and
Self-attention for Visual Recognition" ](https://arxiv.org/pdf/2201.09450.pdf). Would you kindly tell me the reference of this split block? 

Thank you and best regards!

**Comment by Andy1621** [comment]
Sorry for late response. 
`SplitSABlock` refers to dividing spatial and temporal attention. You can find the results in Table 11 (where `Joint` is ×).

**Comment by x2ss** [comment]
> Sorry for late response. `SplitSABlock` refers to dividing spatial and temporal attention. You can find the results in Table 11 (where `Joint` is ×).

Got it! Thanks for your help!
