### ISSUE TITLE
Hope to get a copy of the data stored in BaiduYun

### ISSUE THREAD

**Issue by SKBL5694** [Sense-X/UniFormer#101]
Download the data from origin url is too slow, can you share a download url by BaiduYun?

**Comment by SKBL5694** [comment]
I found you've shared a BaiduYun data, but the url is out of date now.

**Comment by Andy1621** [comment]
URL: https://pan.baidu.com/s/13Bf-BLWMiMvN5MRQKViwJw  Password: gwrs

**Comment by SKBL5694** [comment]
执行unzip train_k400.zip报错
Archive:  train_k400.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.

**Comment by Andy1621** [comment]
Can you try to use `tar zxvf` train_k400.zip? Since this dataset has been uploaded for a long time, I'm not sure whether they are a `.zip` file or a `.tgz` file.

**Comment by SKBL5694** [comment]
It works, thx and happy new year :)
