### ISSUE TITLE
How to process video data into the form of new_k400?

### ISSUE THREAD

**Issue by SKBL5694** [Sense-X/UniFormer#104]
I want to resize my custom video data  to the short edge size of 320 like new_k400, but I am only familiar with the python. Do you have any good suggestion? Or maybe you can tell me how do you process the origin k400 data to the new_k400. Thanks a lot.

**Comment by Andy1621** [comment]
I notice that you have downloaded the videos from BaiduYun. They have been resized to the short edge size of 320! You just need to run the training.

**Comment by Andy1621** [comment]
For your training data, you do not need to resize them. Resizing 320 is for faster loading. If your data size is small, you do not need to resize them. To resize video, you can follow [MMAction2](https://github.com/open-mmlab/mmaction2/blob/40cb52e57ffbaca4cbdad3de3de47f43aace65ab/tools/data/resize_videos.py).
