### ISSUE TITLE
One 7x7 conv vs. two 3x3 conv

### ISSUE THREAD

**Issue by LMMMEng** [Sense-X/UniFormer#111]
Thank you for your wonderful work!

Is two 3x3 convs (stride=2) substituted for one 7x7 conv (stride=4) as stem because the former leads to better results?

**Comment by Andy1621** [comment]
Yes. Double 3x3 convs not only save computation, but also achieve a little better results.

**Comment by LMMMEng** [comment]
Thank you! Do you remember exactly how much improvement there was on ImageNet?

**Comment by Andy1621** [comment]
Sorry, I'm not sure. But double 3x3 conv is a popular modification in current vision transformers. You can simply adopt the better setting.

**Comment by LMMMEng** [comment]
Got it, thank you!
