### ISSUE TITLE
The model and log links for the ucf101 and hmdb51 datasets are no longer valid

### ISSUE THREAD

**Issue by Chunsheng13** [Sense-X/UniFormer#113]
Dear author, hello. The model and log links for the ucf101 and hmdb51 datasets are no longer valid. Can you share them again or send them to my email address zcs0228@126.com. Thank you

**Comment by Andy1621** [comment]
Sorry, I forget to upload the corresponding model. I will upload it later.

**Comment by Andy1621** [comment]
Please check it in README.

**Comment by Chunsheng13** [comment]
Thank you very much
