### ISSUE TITLE
About the pretrain model

### ISSUE THREAD

**Issue by BaoliangChen-stu** [Sense-X/UniFormer#114]
I can not found the pretrained backbone. Where is the pretrained backbonet

**Comment by Andy1621** [comment]
which one do you need?

**Comment by chenbaoliang123** [comment]
> which one do you need? All of them can be found [here](https://github.com/Sense-X/UniFormer/tree/main/image_classification).

I want Uniformer-Bh14 for Instance Segmentation in my dataset. whicn pretrained model should I download.

**Comment by Andy1621** [comment]
please check the corresponding `run.sh` to find the model. For you problem [here](https://github.com/Sense-X/UniFormer/blob/main/semantic_segmentation/fpn_seg/exp/fpn_hybrid_base/run.sh), the model is `uniformer_base_in1k.pth`.
