### ISSUE TITLE
SABlock is the same as SABlock_windows？

### ISSUE THREAD

**Issue by mywebinfo65536** [Sense-X/UniFormer#116]
![SABlock_Windows](https://github.com/Sense-X/UniFormer/assets/105631236/acb99eac-3391-4258-904e-d4a72674713a)
（1）SABlock_Windows structure
![SABlock](https://github.com/Sense-X/UniFormer/assets/105631236/9a33d952-f04e-4ccc-9562-eea0521d4be2)
（2）SABlock structure

I found them the same, why ?

**Comment by Andy1621** [comment]
Yes, the structure is the same (thus the pretrained parameter can be loaded), but the operation is different. Please check https://github.com/Sense-X/UniFormer/blob/f92e423f7360b0026b83362311a4d85e448264d7/object_detection/mmdet/models/backbones/uniformer.py#L192-L210

The window block is used to reduce the computation for large-resolution input.

**Comment by mywebinfo65536** [comment]
Okey, thanks for your answer.
