### ISSUE TITLE
Error in loading videos for testing

### ISSUE THREAD

**Issue by mr17m** [Sense-X/UniFormer#117]
Hi,
I trained my video classification model using the trainer of this repository and I used the annotation files (csv files) in data_list folders but because I only used limited number of video classes for training I removed other annotations for other classes in the csv files and I renamed the classes from 0 to N and also I was careful to apply such changes in the "[kinetics_400_categroies.txt](https://github.com/Sense-X/UniFormer/blob/main/video_classification/data_list/k400/kinetics_400_categroies.txt)". Plus, I extracted the videos from their class folders and I put all the videos in a specific folder for testing and also training. 

I used this argument for the train "_C.DATA.PATH_LABEL_SEPARATOR = "," " and no error appeared. So I use the same for the test but I see the following error:

![Untitled](https://github.com/Sense-X/UniFormer/assets/128163133/4712d2c9-17c0-4028-939b-e8b8fca15479)

Any idea what is wrong?

**Comment by Andy1621** [comment]
Can you try to print the `label` and see its type? It is possible the `label` is an empty string, because there is some error in you annotation file.

**Comment by mr17m** [comment]
@Andy1621 I solved the previous issue but I still face a new error. The question is updated with the new error. It is worthy to mention that I use the csv files in the repository but I only removed other classes in the csv files because I trained and want to test on only 25 classes. What is wrong?

**Comment by Andy1621** [comment]
There are some errors when loading the video. You can print the path of the video and check whether it is correct.

BTW, for an issue, you can post a new bug instead of changing the previous content, thus others can follow your issues.

**Comment by mr17m** [comment]
@Andy1621 , Thanks for the comment. I printed out the path of the videos but it is correct. Do you have any idea what is wrong?
![unif](https://github.com/Sense-X/UniFormer/assets/128163133/53377754-b70d-4f8e-aa37-2ba51a5a99bc)

**Comment by Andy1621** [comment]
Sorry for the late response! You can try to set `num_worker=0`, thus it may present the correct error message.

**Comment by mr17m** [comment]
I did but I faced with the following error:
![error](https://github.com/Sense-X/UniFormer/assets/128163133/1824beb2-f96a-4ce1-8588-ad9bf4aef834)

**Comment by Andy1621** [comment]
Check the log, and you can find `persistent_workers` should be `False` when `num_workers` is 0.
