### ISSUE TITLE
which pretrain model is uniformer-small-dim64？

### ISSUE THREAD

**Issue by wanzhen666** [Sense-X/UniFormer#124]
![image](https://github.com/Sense-X/UniFormer/assets/56305119/d91f994a-95dc-4bf5-aec9-401ef8d29d9c)
后两个模型是一个是dim32 一个是dim64，请问第一个模型的dim是多少呢，我有点分不清，我想把它作为我下游任务的骨干网络，替换swintiny，请问你建议我用哪个？ 非常感谢您

**Comment by wanzhen666** [comment]
另外small和small-plus有什么区别吗

**Comment by wanzhen666** [comment]
抱歉，small-和small-plus的区别我在论文中看到了，我想把它用于我下游任务，是应该用small版本的吗，也就是图片中的第一个权重？他的head_dim是64吗？ @Andy1621

**Comment by Andy1621** [comment]
small或者small_plus_dim64都可以，dim64速度会稍微快点

**Comment by wanzhen666** [comment]
非常感谢你，我用了uniformer-small-224作为我下游任务的backbone，它确实有用，请问关于tokenlabing的模型，如果我想用的话，只需要下载新的预训练权重吗，还是说下载新的预训练权重后，代码中需要加图片中红框的那部分，因为我没有用到最后的分类头，只用到了四个block。非常期待你的回复，祝您身体健康，科研顺利！
![1702185208336](https://github.com/Sense-X/UniFormer/assets/56305119/9eac06a2-fa8f-4d1f-8c19-4e0c271b52e9)

**Comment by Andy1621** [comment]
不需要的
