### ISSUE TITLE
can't find the tlt.data module?

### ISSUE THREAD

**Issue by RyanHuangNLP** [Sense-X/UniFormer#13]
in the token labeling [main file](https://github.com/Sense-X/UniFormer/blob/main/image_classification/token_labeling/main.py), I found that `from tlt.data import create_token_label_target, TokenLabelMixup, FastCollateTokenLabelMixup, create_token_label_loader, create_token_label_dataset` ,
but I can't find the tlt.data module
![image](https://user-images.githubusercontent.com/49582480/154901434-14c1fd22-5311-43e0-b6b8-9bf214cc8cf4.png)

**Comment by Andy1621** [comment]
Very sorry for the late response. I have fixed the bug in the new version. It is because I add 'data' in `.gitignore` file.

**Comment by Andy1621** [comment]
As there is no more activity, I am closing the issue, don't hesitate to reopen it if necessary.

**Comment by RyanHuangNLP** [comment]
@Andy1621 Thanks for responsing, another question is the UniFormer-L model config is following?

```
@register_model
def uniformer_base_ls(pretrained=True, **kwargs):
    global layer_scale
    layer_scale = True
    model = UniFormer(
        depth=[5, 8, 20, 7],
        embed_dim=[64, 128, 320, 512], head_dim=64, mlp_ratio=4, qkv_bias=True,
        norm_layer=partial(nn.LayerNorm, eps=1e-6), **kwargs)
    model.default_cfg = _cfg()
    return model
```

**Comment by Andy1621** [comment]
Yes! The `head_dim` of other models are 32 but 64 for the large model.

**Comment by RyanHuangNLP** [comment]
@Andy1621 Got it
