### ISSUE TITLE
Feature Extraction

### ISSUE THREAD

**Issue by JonathanFlores2503** [Sense-X/UniFormer#133]
I found your paper extremely interesting and I am very interested in it. I would like to use it for feature extraction. I saw that you provided a demo here [app.py](https://huggingface.co/spaces/Sense-X/uniformer_video_demo/blob/main/app.py) but I'm not entirely clear on whether that code would serve for this purpose or how I could use your code as a feature extractor. Currently, I'm working with video classification. Could you possibly assist me with this?

**Comment by Andy1621** [comment]
You can simple return the features by `detach()` to reuse them.
