### ISSUE TITLE
How do I use Uniformer for semantic segmentation

### ISSUE THREAD

**Issue by long123524** [Sense-X/UniFormer#18]
How do I use Uniformer for semantic segmentation?

**Comment by Andy1621** [comment]
You can simply follow the [README](https://github.com/Sense-X/UniFormer/tree/main/semantic_segmentation) for semantic segmentation. We follow the popular setting in MMSegmentaion.

**Comment by Andy1621** [comment]
As there is no more activity, I am closing the issue, don't hesitate to reopen it if necessary.
