### ISSUE TITLE
Some questions about video classification.

### ISSUE THREAD

**Issue by RongchangLi** [Sense-X/UniFormer#21]
Hello, this is a great work. But there are something I want to ask:
1.How to prepare the train and val list file for Something-Something V1 dataset? Are these of the same format of Something-Something V2 mentioned in dataset.md? Can you please provide those?

2. I ever adopt the tools in TSM project to extract frames of Something-Something V2. The difference is that the extracted frames are sparse. For example, according to the train.csc you provide in dataset.md the frames of video 1 is totally  117 while in TSM project the number is 45. So, why do you adopt a much dense extracting rate? How do different rates influence the final performance?

**Comment by Andy1621** [comment]
Thanks for your question. 

For Something-SomethingV1, I remember that 20BN provides the extracted frames. 
For Something-SomethingV2, as claimed in my [README](https://github.com/Sense-X/UniFormer/blob/main/video_classification/DATASET.md), you have to extract the frames at **30 FPS**. Such dense extracting is a common setting in MMAction. Such settings improve the performance slightly (<0.5% top-1 accuracy).

**Comment by RongchangLi** [comment]
> Thanks for your question.
> 
> For Something-SomethingV1, I remember that 20BN provides the extracted frames. For Something-SomethingV2, as claimed in my [README](https://github.com/Sense-X/UniFormer/blob/main/video_classification/DATASET.md), you have to extract the frames at **30 FPS**. Such dense extracting is a common setting in MMAction2. It wii improve the performance slightly (<0.5% top-1 accuracy).

Thanks for your explaination. But I am still a little confused. So, for SS-V1, I should use the files such as  **somesomev1_rgb_{}_split.txt** in [./data_list/sthv1/](https://github.com/Sense-X/UniFormer/tree/main/video_classification/data_list) to bulid dataset. For SS-V2, I should download  all the annotation json files and the frame lists you provide to build dataset. Is that so?

**Comment by Andy1621** [comment]
Actually, for SSV2, the annotation JSON files contain the object labels. 
The frame lists I provided only contain paths and labels. You can simply extract video at 30FPS, thus the frame number will be the same.

**Comment by RongchangLi** [comment]
> Actually, for SSV2, the annotation JSON files contain the object labels. The frame lists I provided only contain paths, frame numbers, and labels. You can simply extract videos at 30FPS, thus the frame numbers will be the same.

Oh, It seems that I have found that what I am confused of. Actually I just need to use the split files in [./data_list/sthv2](https://github.com/Sense-X/UniFormer/tree/main/video_classification/data_list/sthv2) to build SS-V2 dataset (If I re-extract frames with 30 FPS). The annotation JSON files can be used to create these split files. My confusion is from the [tran](https://dl.fbaipublicfiles.com/pyslowfast/dataset/ssv2/frame_lists/train.csv) in [DATASET.md](https://github.com/Sense-X/UniFormer/blob/main/video_classification/DATASET.md). It seems that the [train.csv ](https://dl.fbaipublicfiles.com/pyslowfast/dataset/ssv2/frame_lists/train.csv) and [val.csv](https://dl.fbaipublicfiles.com/pyslowfast/dataset/ssv2/frame_lists/train.csv) won't be used in building dataset object. But they are referred when extracting frames. Is that so?

**Comment by Andy1621** [comment]
I remember that all the videos are in one directory. You can just extract all the videos, and find the train/val videos according to the provided split files.

**Comment by Andy1621** [comment]
Moreover, the train/val files in DATASET.md are provided by MMAction. You can simply use the file in [data_list/sthv2](https://github.com/Sense-X/UniFormer/tree/main/video_classification/data_list/sthv2).

**Comment by RongchangLi** [comment]
> Moreover, the train/val files in DATASET.md are provided by MMAction. You can simply use the file in [data_list/sthv2](https://github.com/Sense-X/UniFormer/tree/main/video_classification/data_list/sthv2).

OK, thanks very much!

**Comment by Andy1621** [comment]
As there is no more activity, I am closing the issue, don't hesitate to reopen it if necessary.
