### ISSUE TITLE
Some question on pretrained model usage

### ISSUE THREAD

**Issue by Gray-OREO** [Sense-X/UniFormer#23]
Hi, @Andy1621 ,

I want to use pretrained UniFormer as the backbone for a downstream task on the video. But I can't obtain a simple but usable network code just by `UniFormer-main\video_classification\slowfast\models\uniformer.py`.

I annotate the code about UniFormer register, and define the offered "config.yaml" for UniFormer instantiation. But there is an error that some parameters is lacking in config file, like "qkv_bias = cfg['UNIFORMER']['QKV_BIAS']".

Thanks!

**Comment by Andy1621** [comment]
@Gray-OREO Thanks for your question. You can find the model code [here](https://huggingface.co/spaces/Sense-X/uniformer_video_demo/blob/main/uniformer.py).

I have used it to create a demo.

**Comment by Gray-OREO** [comment]
@Andy1621 ，

Thanks for your quick response! It's very useful.
