### ISSUE TITLE
The convolution kernel parameter problem of patch embedding in the first stage of video classification

### ISSUE THREAD

**Issue by 834799106** [Sense-X/UniFormer#31]
Hi, thank you so much for your work. I am now faced with a 3D input task, so I would like to refer to your work. Different from the video, the three dimensions of my data are equally important. Therefore, I understand that the convolution kernel parameter of patch embedding in the first stage should be changed to 4x4x4 with stride  4x4x4, right? However, WHEN I realized this problem, I have trained a batch of models, and the convolution kernel of these models is still 3x4x4, and the step size is 4x4x4. Here I want to ask you what impact will be produced by the difference of this parameter?

**Comment by Andy1621** [comment]
这个应该是有影响的，相当于你用3x4x4的卷积核，4x4x4的stride，会跳过一些channel不参与运算，漏掉了部分信息。另外需要注意权重需要用2D训练的图像模型进行inflate，代码里面是写了的

**Comment by 834799106** [comment]
好的，谢谢老师

**Comment by Andy1621** [comment]
莫事，随时交流

**Comment by LEM0NTE** [comment]
> 莫事，随时交流

您好。我注意到您的工作在stage3，4的时候，是采用kernel size=（1，2，2）进行patch embedding的。所以我理解您的方式应该等同于ViViT中的如图所示
![image](https://user-images.githubusercontent.com/74885294/188314232-1c66791e-a31e-491b-8728-1679360f7068.png)
但ViViT还提供了另一种tubelet embedding的思路，即下图
![image](https://user-images.githubusercontent.com/74885294/188314265-e68e17ce-f272-486c-b309-fad6464c451d.png)
如果采用这样的patch embedding。或许3dconv的卷积核应当设置为例如
nn.Conv3d(inp, oup, (2, 2, 2), (2, 2, 2), (0, 0, 0), groups=groups)
所以您为什么选择了第一种而没有采用第二种方式呢？
