### ISSUE TITLE
How to fine-tune the pre-trained on Imagenet with 384x384 resolution?

### ISSUE THREAD

**Issue by yunh-w** [Sense-X/UniFormer#34]
How to fine-tune the pre-trained on Imagenet with 384x384 resolution?
I pre-train the model on Imagenet1k but I meet this KeyError when I try to fine-turn.

![image](https://user-images.githubusercontent.com/82502517/162205148-6c0bbb1d-cafd-40da-b6bd-83c904933ac2.png)

**Comment by Andy1621** [comment]
You can simply comment these codes since I never use it.

**Comment by yunh-w** [comment]
@Andy1621 Thanks!

**Comment by Andy1621** [comment]
As there is no more activity, I am closing the issue, don't hesitate to reopen it if necessary.
