### ISSUE TITLE
How to convert video classification from pytorch to onnx，on cpu

### ISSUE THREAD

**Issue by LeiYiNuist** [Sense-X/UniFormer#36]
I want to convert the pytorch model to the onnx model on the cpu, but there is no relevant code in the source code. Can you upload pytorch2onnx.py in the video classification?

**Comment by Andy1621** [comment]
I'm so sorry that I never try to convert the PyTorch model to the onnx model. 
Actually, as I know, there is no relevant code to convert Vision Transformer to the onnx model......

**Comment by LeiYiNuist** [comment]
Oh, that's kind of interesting, I just converted it to onnx. However, thank you very much for taking the time to reply to me.

**Comment by Andy1621** [comment]
As there is no more activity, I am closing the issue, don't hesitate to reopen it if necessary.
