### ISSUE TITLE
Video classification, k400 test, top1 is only 0.03

### ISSUE THREAD

**Issue by LeiYiNuist** [Sense-X/UniFormer#38]
I ran the test code before and found that top1 is only 0.03. I can guarantee that my data and labels must be aligned. Because there is no dataset provided by the author, I can only find the dataset on the Internet, so the labels I use, they are all generated by myself based on the data set, but the results that came out were so disappointing to me. In previous issues, I found that other people also had this problem, and then I based on the [kinetics_400_categroies.txt](https://github.com/SenseX/UniFormer/blob/main/video_classification/data_list/k400/kinetics_400_categroies.txt) provided by the author
, the test.csv is regenerated, which means that the test.csv file must be regenerated using the kinetics_400_categroies.txt provided by the author . Then I ran it again with the new kinetics_400_categroies.txt and test.csv, this time with a top1 of 0.81. This is really weird. This is really weird. This is really weird,

**Comment by Andy1621** [comment]
Can you provide the LOG file and the test.csv? I'm not sure whether you have already loaded the models correctly.
1. Maybe you should check your log like [Here](https://github.com/Sense-X/UniFormer/issues/30).
2. Moreover, our Kinetics dataset can be downloaded from [BaiduYun](https://pan.baidu.com/s/12iIohkupXEVdVMPohtd4Kg), the password is `vpgd`.
```
cat xa* | tar xj
```

Since the [Video Demo](https://huggingface.co/spaces/Sense-X/uniformer_video_demo) works in huggingface and the pre-trained models are good for other video tasks, I'm sure the weights are correctly uploaded.

**Comment by LeiYiNuist** [comment]
Maybe it's my problem, but fortunately, the problem has been solved. Thank you very much!
Oh, by the way, can you tell me where your data preprocessing code is? Data preprocessing about test.

**Comment by Andy1621** [comment]
Thanks for your try! You can explain the problems you meet, thus others can avoid it~~

As for the data preprocessing, if you only want to test, you can reuse the code in my [Video Demo](https://huggingface.co/spaces/Sense-X/uniformer_video_demo/blob/main/app.py#L33-L62).

**Comment by LeiYiNuist** [comment]
Using the kinetics_400_categroies.txt you provided, I generate test.csv, top1 can reach ~0.82
![C{ OC7YOG7O@S8P OD`7G~3](https://user-images.githubusercontent.com/32995626/164457369-7ebbe8b0-ad85-4d0a-9fe4-4790eac11058.png)


But if I have a kinetics_400_categroies.txt (the contents in it are sorted according to A-Z), and I generate test.csv, the top1 is only 0.03.
![DCO TQT{)9I6B_7Q@11P 1U](https://user-images.githubusercontent.com/32995626/164457359-e1b7c623-c262-455d-acba-040ac3624475.png)

**Comment by Andy1621** [comment]
Hi! Does the `0.82` means `82%`? If it means `82%`, the testing is correct.

**Comment by Andy1621** [comment]
I have thought `0.82` means `0.82%`......
Because we use different label indexes, it is sure that the accuracy is low ~~
Thanks for your try!

**Comment by LeiYiNuist** [comment]
eeee，I mean top1 is 81.63 and 0.03

**Comment by Andy1621** [comment]
As there is no more activity, I am closing the issue, don't hesitate to reopen it if necessary.
