### ISSUE TITLE
There is an image output during training and validation, but not during testing

### ISSUE THREAD

**Issue by pu-1** [Sense-X/UniFormer#39]
What is the reason why the trained model predicts the image to be blank when testing the image?

**Comment by Andy1621** [comment]
Sorry, I do not understand the problem you meet. You can follow what I use in [Image Demo](https://huggingface.co/spaces/Sense-X/uniformer_image_demo).

The codes are [here](https://huggingface.co/spaces/Sense-X/uniformer_image_demo/blob/main/app.py#L13-L31).

**Comment by Andy1621** [comment]
As there is no more activity, I am closing the issue, don't hesitate to reopen it if necessary.
