### ISSUE TITLE
about uniformer

### ISSUE THREAD

**Issue by PJJie** [Sense-X/UniFormer#4]
Where is the uniformer module referenced? Is the uniformer a plug and play module? For example, I have an input of (64,3,25,25). After inputting the uniformer module, will the output also be (64,3,25,25)?

**Comment by Andy1621** [comment]
In my opinion, all blocks based on Transformer block is 'plug-and-play' (the tensor shape is kept after processing).
You can found the code in:
https://github.com/Sense-X/UniFormer/blob/2e91169cddf8f85629e37756c5480c62fe8b253c/image_classification/models/uniformer.py#L105
