### ISSUE TITLE
The log for UniFormer-Sh14 on Cascade Mask R-CNN is the same with that of UniFormer-Bh14

### ISSUE THREAD

**Issue by hhb072** [Sense-X/UniFormer#43]
Thanks for sharing this great work.

It seems that the log for for UniFormer-Sh14 on Cascade Mask R-CNN has been misplaced and the provided one is the same with UniFormer-Bh14's. 

Can you update it with the correct one?

**Comment by Andy1621** [comment]
Thanks for your feedback, I have updated the url.
Actually, you can find all the logs in [Google Drive](https://drive.google.com/drive/folders/12wFRaILxeITdCNYZj1S38n4iaNn9trt8?usp=sharing), which I added in README.

**Comment by Andy1621** [comment]
As there is no more activity, I am closing the issue, don't hesitate to reopen it if necessary.
