### ISSUE TITLE
exp 文件夹中文件名的含义

### ISSUE THREAD

**Issue by Holmes-GU** [Sense-X/UniFormer#44]
您好，在exp文件夹中有uniformer_n1_n2_n3形式文件夹。n1格式有b8x8，b16，s8x8，s16,这里的s以及b代表的是模型大小吧？那后面的16以及8x8是什么意思呢？

**Comment by Andy1621** [comment]
For video classification, it means the number of frames. For Kinetics, we use dense sampling. For Sth-Sth, we use uniform (sparse) sampling.

`uniformer_b16x4_k400` refers to training UniFormer-Base on Kinetics-400, and it will sample 16 frames with a frame stride of 4.
`uniformer_b16_sthv2_prek400` refers to training UniFormer-Base on Sth-SthV2 and the model is pre-trained on Kinetics-400, it will uniformly sample 16 frames.

Actually, you can find the corresponding folder for different experiments in [README](https://github.com/Sense-X/UniFormer/blob/main/video_classification/README.md). I have set the URLs for different experiments, please see the corresponding run.sh/config.yaml.

**Comment by Andy1621** [comment]
As there is no more activity, I am closing the issue, don't hesitate to reopen it if necessary.
