### ISSUE TITLE
Regular MS aug for object detection for uniformer

### ISSUE THREAD

**Issue by lxtGH** [Sense-X/UniFormer#47]
Hi! Thanks for sharing the code. It seems that Uniformer uses DETR-like aug for MS training.   (https://github.com/Sense-X/UniFormer/blob/0b5af7de8ccdd196167910674ac7c2061b296c54/object_detection/exp/mask_rcnn_3x_ms_hybrid_small/config.py#L30)
What are the results for regular MS aug for Uniformer for Object Detection?

**Comment by Andy1621** [comment]
Thanks for your question! We simply follow the settings used in [Swin](https://github.com/SwinTransformer/Swin-Transformer-Object-Detection/blob/master/configs/swin/mask_rcnn_swin_tiny_patch4_window7_mstrain_480-800_adamw_3x_coco.py). We do not try other aug for fair comparison.

**Comment by lxtGH** [comment]
Got it~ Thanks for your reply.
