### ISSUE TITLE
drop_path_rate on ade20k

### ISSUE THREAD

**Issue by ydhongHIT** [Sense-X/UniFormer#48]
Thanks for giving the details of drop_path_rate on ade20k. I want to ask how the value of drop path rate affects the performance. Could you provide some comparative results?

**Comment by Andy1621** [comment]
For ADE20K, we mostly follow the `drop_path_rate` in other papers. 
For Semantic FPN, we use a small `drop_path_rate` (0.1 for UniFormer-S and 0.2 for UniFormer-B).
For UperNet, we double the `drop_path_rate` (0.2/0.25 for UniFormer-S and 0.4 for UniFormer-B).
The results are similar if using 0.05 larger `drop_path_rate`.

**Comment by Andy1621** [comment]
As there is no more activity, I am closing the issue, don't hesitate to reopen it if necessary.

**Comment by ydhongHIT** [comment]
> For ADE20K, we mostly follow the `drop_path_rate` in other papers. For Semantic FPN, we use a small `drop_path_rate` (0.1 for UniFormer-S and 0.2 for UniFormer-B). For UperNet, we double the `drop_path_rate` (0.2/0.25 for UniFormer-S and 0.4 for UniFormer-B). The results are similar if using 0.05 larger `drop_path_rate`. We simply improve the `drop_path_rate` if we find the mIoU changes slowly in the later iterations.

Thanks for your reply. May I ask what the later iterations mean? For example, the total number is 160k, the scope of later iterations is what?

**Comment by Andy1621** [comment]
I test the mIoU every 80k iterations. 
When I find the mIoU changes slowly or even drops in the later eval iterations, which means the model overfits, I will improve the `drop_path_rate`.
