### ISSUE TITLE
Gradio Blocks demo

### ISSUE THREAD

**Issue by AK391** [Sense-X/UniFormer#49]
Hi, great work on the demo for uniformer https://huggingface.co/spaces/Andy1621/uniformer_image_demo, would you be interested in making a gradio blocks version of this for the blocks event this month: https://huggingface.co/Gradio-Blocks or for another model, thanks!

**Comment by Andy1621** [comment]
Thanks for your invitation. I have added the image and video demo in Gradio-Blocks~~

**Comment by AK391** [comment]
@Andy1621 thanks, could you update the demo to use the gradio blocks feature (see the documentation for this here: https://gradio.app/introduction_to_blocks/) and also the sdk can be updated by adding 
`sdk_version: 3.0.2` for example here after the sdk line https://huggingface.co/spaces/Gradio-Blocks/uniformer_video_demo/blob/main/README.md#L6

**Comment by Andy1621** [comment]
@AK391 Thanks for your great suggestion! I have updated the code and used the gradio blocks feature. It works well!

**Comment by AK391** [comment]
@Andy1621 great thanks for updating demo looks great, please also share the competition with anyone else who might be interested

**Comment by Andy1621** [comment]
@AK391 Okay, I will share it with my friends. BTW, I have made more demos for [Detection](https://huggingface.co/spaces/Gradio-Blocks/uniformer_image_detection) and [Segmentation](https://huggingface.co/spaces/Gradio-Blocks/uniformer_image_segmentation).
