### ISSUE TITLE
meaning of #Frame 

### ISSUE THREAD

**Issue by x2ss** [Sense-X/UniFormer#5]
Hi, 

Thanks for sharing this impressive work.

When I read the paper, I feel puzzled about #Frame in TABLE 3. (Comparison with the state-of-the-art on Kinetics400&600) in the paper https://arxiv.org/pdf/2201.09450.pdf. As for UniFormer-S， the #Frame is 16×1×4, what do 16,1, and 4 represent for？ 

Best regards！

**Comment by Andy1621** [comment]
**#Frame = number_of_frames x number_of_crops x number_of_clips.**
#Frame = 16x1x4 means we perform **multi-clip testing** with 4 clips and 1 center crops.
#Frame = 16x3x1 means we perform **multi-crop testing** with 1 clip and 3 crops (left, center and right).

In previous, CNNs[1] often adopts multi-crop and multi-clip testing at the same time, e.g., 16x3x10.
Recent video Transformers usually adopt multi-clip testing for Kinetics and multi-crop testing for Sth-Sth [2].

More analyses n [our paper](https://arxiv.org/abs/2201.09450). 


[1] Feichtenhofer C, Fan H, Malik J, et al. Slowfast networks for video recognition[C]//Proceedings of the IEEE/CVF international conference on computer vision. 2019: 6202-6211.
[2] Fan H, Xiong B, Mangalam K, et al. Multiscale vision transformers[J]. arXiv preprint arXiv:2104.11227, 2021.

**Comment by Andy1621** [comment]
Some hyperparameters can also be found in `config.yaml` and `run.sh`.
Please refer to [README](https://github.com/Sense-X/UniFormer/tree/main/video_classification).

Multi-clip testing for Kinetics
```python
TEST.NUM_ENSEMBLE_VIEWS 4
TEST.NUM_SPATIAL_CROPS 1
```

Multi-crop testing for Sth-Sth
```python
TEST.NUM_ENSEMBLE_VIEWS 1
TEST.NUM_SPATIAL_CROPS 3
```

**Comment by x2ss** [comment]
> **#Frame = number_of_frames x number_of_crops x number_of_clips.** #Frame = 16x1x4 means we perform **multi-clip testing** with 4 clips and 1 center crops. #Frame = 16x3x1 means we perform **multi-crop testing** with 1 clip and 3 crops (left, center and right).
> 
> In previous, CNNs[1] often adopts multi-crop and multi-clip testing at the same time, e.g., 16x3x10. Recent video Transformers usually adopt multi-clip testing for Kinetics and multi-crop testing for Sth-Sth [2].
> 
> More analyses can be found in Figure 7 in [our paper](https://arxiv.org/abs/2201.09450).
> 
> [1] Feichtenhofer C, Fan H, Malik J, et al. Slowfast networks for video recognition[C]//Proceedings of the IEEE/CVF international conference on computer vision. 2019: 6202-6211. [2] Fan H, Xiong B, Mangalam K, et al. Multiscale vision transformers[J]. arXiv preprint arXiv:2104.11227, 2021.

Thanks for your kind reply. 

As stated in [2], "the input to the network are T frames with a temporal stride of τ ; denoted as T × τ". As far as I concerned, this is the sampling method  in[ readme ](https://github.com/Sense-X/UniFormer/tree/main/video_classification). 

So is there is any relationship between the #Frame and sampling method? If the #Frame = 16x3x10, what is the input to the network for one inference? 

Best regards!

**Comment by Andy1621** [comment]
In fact, **#Frame** means the total input frames for testing.
For #Frame = 16x3x10, one inference will input **16 frames**, but we will **repeat 3x10 times** and finally average all the predictions.

**Comment by x2ss** [comment]
Thanks！
