### ISSUE TITLE
How could I use token labeling for object detection task?

### ISSUE THREAD

**Issue by mitming** [Sense-X/UniFormer#52]

**Comment by Andy1621** [comment]
Thanks for your questions. In my opinion, Token Labeling only works for ImageNet pre-training. You can simply use those models pre-trained with Token Labeling for object detection!

For more details about Token Labeling, please see their [official repo](https://github.com/zihangJiang/TokenLabeling)!

**Comment by Andy1621** [comment]
As there is no more activity, I am closing the issue, don't hesitate to reopen it if necessary.
