### ISSUE TITLE
KeyError: "MaskRCNN: 'UniFormer is not in the backbone registry'"

### ISSUE THREAD

**Issue by liuyafei2021** [Sense-X/UniFormer#55]

**Comment by Andy1621** [comment]
Thanks for your question. You may not install the environment correctly. Please check the issue [here](https://github.com/SwinTransformer/Swin-Transformer-Object-Detection/issues/35).

**Comment by Andy1621** [comment]
As there is no more activity, I am closing the issue, don't hesitate to reopen it if necessary.
