### ISSUE TITLE
[Question for Video Classification] Registering my custom dataset 

### ISSUE THREAD

**Issue by DoranLyong** [Sense-X/UniFormer#56]
Hi, I'm back again with another issue :). 

My goal is to finetune the UniFormer to my custom video dataset.
For this, I need to prepare a proper Pytorch dataset class like in `slowfast/datasets/kinetics.py` first. But, I met a registry issue for my dataset.
![image](https://user-images.githubusercontent.com/13333380/172077059-3c02db63-7828-4547-8bf3-a4d43a802b7d.png)

I followed [issue #149 in FAIR's slowfast github](https://github.com/facebookresearch/SlowFast/issues/149), but in my case, since I prepared my dataset in `Kinetics-400` format, duplicated and retouched `kinetics.py`. 

I'm wasting much time solving this :s ... but, I have no idea which point I missed.

My process is as below.
*** 
### Step1. Copy `kinetics.py` and Rename it into my custom dataset
For example, suppose my dataset name is Boho, I change 1) the python script name and 2) the class name
* `kinetics.py` → `boho.py`. 
*  `Class Kinetics(...)` → `Class Boho(...)`

https://github.com/Sense-X/UniFormer/blob/fdc1a646a3dac81a692877bcffa15e42db8e7df6/video_classification/slowfast/datasets/kinetics.py#L20-L33

![image](https://user-images.githubusercontent.com/13333380/172077417-0c51fb4b-dac9-404a-8cfb-776de942eaa8.png)

### Step2. Adding the line `from .boho import Boho` to the `__init__.py` file in the same folder. 
https://github.com/Sense-X/UniFormer/blob/fdc1a646a3dac81a692877bcffa15e42db8e7df6/video_classification/slowfast/datasets/__init__.py#L4-L10

![image](https://user-images.githubusercontent.com/13333380/172077752-38c0a9da-54aa-4960-b66e-d0d1a070a6f2.png)

### Step3. Rebuild the slowfast package 
``` bash 
~$ python setup.py build develop
```

### Step4. Assign `TRAIN.DATASET = 'boho'` in `config.yaml`
![image](https://user-images.githubusercontent.com/13333380/172078018-185a8c6a-52e9-40ad-91a3-896d54604a85.png)

*** 
I learned that the decorator `@DATASET_REGISTRY.register()` is to register my data object into `fvcore` `Registry`, but still is not yet.  

Can you give me feedback on which part I missed?

**Comment by Andy1621** [comment]
I believe you have followed the right steps since I also register datasets like you [here](https://github.com/Andy1621/Nightcrawler/blob/41cbaad6e5e4cdbfa4e0647adbe188eb5949ca10/slowfast/datasets/__init__.py#L11).

You can try to print the dataset names via and check the bug...
```python
print(DATASET_REGISTRY._obj_map)
```

Actually, the step3 can be ignored. The repo does not need to be rebuilt.

**Comment by DoranLyong** [comment]
Okay, I found out the problem. That was related to the python path issue. 
I duplicated another `slowfast` project and the dataset registry scoped that workspace where there is not my custom dataset. 
After making it ignoring that path, everything works well :) thank. 

By the way, you are doing another interesting project.  I would also check it later! 

Thanks for your sharing

**Comment by Andy1621** [comment]
Thanks for your reply. Don't forget to add PYTHONPATH when running your experiment.
https://github.com/Sense-X/UniFormer/blob/1ce70bcccbe72962813aedf5eb1209f318f859b6/video_classification/exp/uniformer_s16x4_k400/run.sh#L2

**Comment by manhcntt21** [comment]
Hi, i have same problem, please, help me @DoranLyong. 

These step I have done.

1 Create file: MyDataset.py, copy from Kinetics.py
2 add 
```
from .custom_data import MyDataset
``` in __init__.py
