### ISSUE TITLE
accuracy of k400

### ISSUE THREAD

**Issue by W4ngH4o** [Sense-X/UniFormer#57]
I have read the log file of 8x1x4. I find that the error rate of val dataset in the training process is 31.35 and the test accuracy rate of 8x1x1  is 74.41.  As far as I am concerned, the val dataset and the test dataset are the same. So I want to know why the two results are different. Thanks for your reply.

**Comment by W4ngH4o** [comment]
Thanks so much. I understood.

**Comment by Andy1621** [comment]
As there is no more activity, I am closing the issue, don't hesitate to reopen it if necessary.
