### ISSUE TITLE
about video classification

### ISSUE THREAD

**Issue by Auroralyxa** [Sense-X/UniFormer#59]
Hi,
I have three operational questions about video classification 
1.I don't know how to  resize the video to the short edge size of 320,Could you please provide me with the processed video, my email is 2273740426@qq.com
2.Can I replace the video with time series image data? The time series image data refers to a large number of images in June and September every year from 2017 to 2021. If possible, which part should I modify?
Thanks in advance

**Comment by Auroralyxa** [comment]
Thank you for your reply.
I am studying crop classification. According to different phenological periods, the characteristics of crops are different, that is to say, the crop images obtained at different times are different, so it is necessary to add temporal features.  
The size of each image is different. Example images are as follows:
<img width="588" alt="微信截图_20220609222103" src="https://user-images.githubusercontent.com/72694606/172869951-8cb19df7-8439-44ea-b51b-0247f7d88faf.png">
If I want to replace the video with time-series images, which part should I modify?

**Comment by Andy1621** [comment]
In my opinion, your dataset seems like a frame-based video dataset.
You can move all the images belonging to the same crop into one directory, and rename them as `00001.png/jpg`, `00002.png/jpg`... (the number increase with the time)
Then you can prepare your meta file like [this](https://github.com/Sense-X/UniFormer/blob/main/video_classification/data_list/k400/train.csv).
For example, if you have 32 time-series images for each crop, and the label are 0 and 1,
```
# path,frame_number,label
crop1,32,0
crop2,32,0
crop3,32,1
crop4,32,1
```

**Comment by Auroralyxa** [comment]
Thank you, I will try as you say

**Comment by Andy1621** [comment]
As there is no more activity, I am closing the issue, don't hesitate to reopen it if necessary.
