### ISSUE TITLE
where is uniformer_small_in1k

### ISSUE THREAD

**Issue by x2ss** [Sense-X/UniFormer#6]
In https://github.com/Sense-X/UniFormer/blob/main/video_classification/exp/uniformer_s16x8_k400/config.yaml

UNIFORMER:
  EMBED_DIM: [64, 128, 320, 512]
  DEPTH: [3, 4, 8, 3]
  HEAD_DIM: 64
  MLP_RATIO: 4
  DROPOUT_RATE: 0
  ATTENTION_DROPOUT_RATE: 0
  DROP_DEPTH_RATE: 0.1
  SPLIT: False
  PRETRAIN_NAME: 'uniformer_small_in1k'

The pretrained model is 'uniformer_small_in1k', however the corresponding model in[ this link](https://drive.google.com/file/d/174muWZJcZHieABDZMKiJ0tNeFLoEkJLx/view) is 'uniformer_small_k400_16x8.pth'. 

Would you kindly tell me where is 'uniformer_small_in1k'?

Thanks and best regards!

**Comment by Andy1621** [comment]
You can find the models in [image_classification](https://github.com/Sense-X/UniFormer/tree/main/image_classification).
[Google Drive](https://drive.google.com/drive/folders/1-sqWoelz3agOG74VkNwadY8RHR28o4Wv), [Baidu Cloud (bdkq)](https://pan.baidu.com/share/init?surl=tLvcwGquAsQdGRAiKR0Jcg)

**Comment by x2ss** [comment]
Thanks！
