### ISSUE TITLE
demo for VideoClassification

### ISSUE THREAD

**Issue by LEM0NTE** [Sense-X/UniFormer#63]
Hi, I am very interested in your project and would like to test  demo videos to explore specific code implementations. But all I see in the README documents are instructions for training and test datasets. Could you please provide a detailed tutorial for the test demo? Thank you very much!

**Comment by Andy1621** [comment]
I have made a demo in [hugging face](https://huggingface.co/spaces/Sense-X/uniformer_video_demo), which can be simply reproduced.

You can follow [app.py](https://huggingface.co/spaces/Sense-X/uniformer_video_demo/blob/main/app.py) to modify your demo!

**Comment by Andy1621** [comment]
By the way, you can create a demo via [jupyter] like my previous work [CT-Net](https://github.com/Andy1621/CT-Net/blob/main/demo/show_cam.ipynb). Due to the difference between CNN and ViT, the CAM is not suitable for UniFormer. You can simply adopt the dataset and inference.

**Comment by LEM0NTE** [comment]
Thanks!
