### ISSUE TITLE
uniformer for object detection

### ISSUE THREAD

**Issue by go-ahead-maker** [Sense-X/UniFormer#68]
Hi, nice work!, but I have a basic question about object detection.

I found that in the mmdetection, some of the pre-defined backbones(e.g., resnet) that with BN layer define the `norm_eval` parameter, and this parameter will be used to decide whether to freeze the BN layer during the training process. I found that Uniformer do use the BN layer in `CABLOCK`, but it seems that you don't use `norm_eval` to freeze the BN layer. Does this mean that BN parameters are also trained during training? And I wonder if this setting has any impact on the training process and final results.

Thanks!

**Comment by go-ahead-maker** [comment]
ohh, I miss the NOTE in the README, but I still wonder how this setting(freeze BN or not) will affect the results since I'm a beginner. Looking forward to your reply!

**Comment by Andy1621** [comment]
In my later experiments, `freeze BN` improve a little.  I suggest you using it!

**Comment by Andy1621** [comment]
As there is no more activity, I am closing the issue, don't hesitate to reopen it if necessary.
