### ISSUE TITLE
Loss function

### ISSUE THREAD

**Issue by LEM0NTE** [Sense-X/UniFormer#69]
您好，我似乎没有在您的论文中看到您关于损失函数的设置细节，并且我不加载预训练权重的情况下训练模型，Top-err以及loss的波动相当剧烈，希望可以得到您的一些帮助或是说明。

**Comment by Andy1621** [comment]
We follow the popular setting to use CE loss for classification and other losses for Detection and Segmentation.
It's normal that the loss varies in the beginning, you can check the log for comparison.

**Comment by Andy1621** [comment]
As there is no more activity, I am closing the issue, don't hesitate to reopen it if necessary.
