### ISSUE TITLE
视频理解中的预训练模型

### ISSUE THREAD

**Issue by LEM0NTE** [Sense-X/UniFormer#71]
您好，我在尝试复现您工作关于action recognition部分的工作时，（以S8*8_K400)为例，发现不能很好的复现出近似的精度。我在测试过程中没有加载任何预训练权重，因此我不确定是不是在ImageNet上预训练的CNN权重的影响。
请问您在训练过程中是如何导入并使用在ImageNet上的预训练权重的，能否给出一个具体详细的说明呢？十分感谢您的耐心解答！

**Comment by Andy1621** [comment]
感谢提问，现有的action recognition比较大的弊端是依赖ImageNet预训练，随机初始化开始训练，需要更多的迭代epoch（参考Fair的一系列工作SlowFast，MViT），更好的方式是利用ImageNet预训练进行视频训练。

关于导入ImageNet预训练权重，可以参考如下代码，主要是对2D卷积进行展开，fc层随机初始化
https://github.com/Sense-X/UniFormer/blob/1ce70bcccbe72962813aedf5eb1209f318f859b6/video_classification/slowfast/models/uniformer.py#L398-L421

**Comment by Andy1621** [comment]
As there is no more activity, I am closing the issue, don't hesitate to reopen it if necessary.
