### ISSUE TITLE
不同服务器训练的模型测试精度偏差过大

### ISSUE THREAD

**Issue by LEM0NTE** [Sense-X/UniFormer#73]
例如。我按照原始的uniformer_s8x8版本训练模型。当我训练了50个epoch后，top1error降到了大约35%左右，因此top1acc应当大约为65%。并且我在该服务器上测试结果也没有问题。但当我把训练得到的.pyth文件搬到另一台服务器上做测试时，top1acc大约在30%左右。出现了相当大的偏差。我把这种情况称为False。多次测试后我简单做了个汇总：
                                                                              V100x2（测试）       TiTan RTXx2（测试）
您提供的s8x8（发布在谷歌网盘中的）                  True（78 acc）       True（78 acc）
在TITAN RTX训练s8x8（top1error=25%）             False（30 acc）      True （76 acc）
在V100训练s8x8（top1error=25%）                      True （76 acc）      False （30 acc）
如上所示，我训练得到的.pyth文件无法迁移到另一台服务器上做测试。两台服务器上的cuda，pytorch，python版本都一致。但出现了如上情况不知道是什么原因，希望得到您的帮助。

**Comment by Andy1621** [comment]
从你的测试结果上看，我们提供的checkpoint在两个平台测试正常，这个看起来并不是代码的问题，而是一个通用的问题，估计是你的环境有些许差别。你可以google搜索更通用的答案，比如“pytorch different testing results on different GPU”。

还有一种可能是你的测试batch size过大，pytorch softmax精度溢出，导致结果差距过大。如果你的batch size比较大的话，可以尝试开小一点。

**Comment by LEM0NTE** [comment]
> 从你的测试结果上看，我们提供的checkpoint在两个平台测试正常，这个看起来并不是代码的问题，而是一个通用的问题，估计是你的环境有些许差别。你可以google搜索更通用的答案，比如“pytorch different testing results on different GPU”。
> 
> 还有一种可能是你的测试batch size过大，pytorch softmax精度溢出，导致结果差距过大。如果你的batch size比较大的话，可以尝试开小一点。

好的我先尝试一下，谢谢您的解答
