### ISSUE TITLE
Patch embedding in Global Uniformer

### ISSUE THREAD

**Issue by LEM0NTE** [Sense-X/UniFormer#76]
您好。我注意到您的工作在stage3，4的时候，是采用kernel size=（1，2，2）进行patch embedding的。所以我理解您的方式应该等同于ViViT中的如图所示
![image](https://user-images.githubusercontent.com/74885294/188314232-1c66791e-a31e-491b-8728-1679360f7068.png)
但ViViT还提供了另一种tubelet embedding的思路，即下图
![image](https://user-images.githubusercontent.com/74885294/188314265-e68e17ce-f272-486c-b309-fad6464c451d.png)
如果采用这样的patch embedding。或许3dconv的卷积核应当设置为例如
nn.Conv3d(inp, oup, (2, 2, 2), (2, 2, 2), (0, 0, 0), groups=groups)
所以您为什么选择了第一种而没有采用第二种方式呢？

_Originally posted by @LEM0NTE in https://github.com/Sense-X/UniFormer/issues/31#issuecomment-1236335370_

**Comment by Andy1621** [comment]
视频网络里一般不会在后几层对temporal维度进行下采样，尽管计算量会比较小，但效果会比较差

**Comment by Andy1621** [comment]
As there is no more activity, I am closing the issue, don't hesitate to reopen it if necessary.
