### ISSUE TITLE
How to calculate GFlops correctly

### ISSUE THREAD

**Issue by LEM0NTE** [Sense-X/UniFormer#80]

**Comment by LEM0NTE** [comment]
哈喽，再...再次感谢您的工作，但我遇到了一个新的问题。我注意到您提供的s8*8_K400模型的计算复杂度为70G
![image](https://user-images.githubusercontent.com/74885294/192422948-38614d64-0d2f-48f3-93b4-045041b03b41.png)
但是在我尝试训练模型时，misc.py: 188: 17.613435904 G
![image](https://user-images.githubusercontent.com/74885294/192423026-b3520451-4db2-46a7-b7e8-99fdf151ca67.png)
为什么这两个值不对应呢，log文件显示的这个17.6G代表的是什么计算复杂度呢

**Comment by W4ngH4o** [comment]
8x1x1: 17.6G
8x1x4: 70G(17.6x4)

**Comment by Andy1621** [comment]
@W4ngH4o You are right. The correct FLOPs should be multiplied by #crop and #clip.
