### ISSUE TITLE
Error when clone

### ISSUE THREAD

**Issue by manhcntt21** [Sense-X/UniFormer#84]
Hi, Thanks for sharing the implementation

I can not use git clone on windows, it raise a error below

`
Cloning into 'UniFormer'...

remote: Enumerating objects: 3489, done.

remote: Counting objects: 100% (71/71), done.

remote: Compressing objects: 100% (38/38), done.

remote: Total 3489 (delta 46), reused 35 (delta 33), pack-reused 3418

Receiving objects: 100% (3489/3489), 28.34 MiB | 5.25 MiB/s, done.

Resolving deltas: 100% (1500/1500), done.

error: invalid path 'image_classification/token_labeling/exp/uniformer_small_dim64_tl_224 /run.sh'

fatal: unable to checkout working tree

warning: Clone succeeded, but checkout failed.

You can inspect what was checked out with 'git status'

and retry with 'git restore --source=HEAD :/'
`

I try to follow, but raise another error, 
`

cd Uniformer
`
and run
`

git restore --source=HEAD :/
`
error
`

error: invalid path 'image_classification/token_labeling/exp/uniformer_small_dim64_tl_224 /run.sh'

error: invalid path 'image_classification/token_labeling/exp/uniformer_small_dim64_tl_224 /test.sh'
`

How to fix this error?

**Comment by Andy1621** [comment]
I have never met this bug. You can try to download the ZIP files directly.

**Comment by manhcntt21** [comment]
Hi, with the help of my friends, i solved the error. So, to help a few windows users like me avoid facing the same problem, you can remove white space character after 'uniformer_small_dim64_tl_224'. Thanks

**Comment by manhcntt21** [comment]
I have made a pull request.

**Comment by Andy1621** [comment]
Thanks for your help!
