### ISSUE TITLE
Training time for kinetics-400

### ISSUE THREAD

**Issue by AbdelrahmanShakerYousef** [Sense-X/UniFormer#96]
Hello,

Thank you for sharing the codebase of your exciting work.

Could you please let me know the training time for pertaining & training on kinetics-400 and the resources you used?

Thank you!

**Comment by Andy1621** [comment]
Thanks for your question.
In my original experiments, all the models are run on a single V100 machine (8GPU) except the largest model.
For detailed training time, you can find the provided logs! It may take ~2 days to train K400 for 110 epochs with 16 frames.

For your experiments, you can use fewer epochs (~55) and fewer frames (~8) to verify your idea fastly.

**Comment by AbdelrahmanShakerYousef** [comment]
Thank you for reply.

According to verifying the idea, shall I pretrain on ImageNet first and then train on K400? If this is the case, how many days your model need to be pretrained on ImageNet ?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Andy1621** [comment]
It's a good question. 
As a new backbone, it needs to be pre-trained on ImageNet first, which will cost 1~2 day. Thus, it actually needs about 3~4 days to verify it on K400.
However, the performance trend is similar. Those models work better on ImageNet often work better on K400.

**Comment by AbdelrahmanShakerYousef** [comment]
Thank you Andy for your reply. Is it 12 days or 34 days? I guess your text is unclear about that.

**Comment by Andy1621** [comment]
1 to 2 days and 3 to 4 days.

**Comment by Andy1621** [comment]
Hi! We have released [UniFormerV2](https://github.com/OpenGVLab/UniFormerV2), which adopts pretrained ViT. It can save a lot of training resources.  Welcome to try it!
